- hosts: all
  vars_files:
    - 'vars/main.yml'
  vars:
    - ruby_mversion: 2.0
    - ruby_fversion: 2.0.0-p247
    - ruby_cversion: 2.0.0p247
  roles:
    - {role: crushlovely.deploy-user}
  tasks:
    - include: 'tasks/main.yml'