---
- name: Check if Ruby is installed
  shell: /usr/bin/test `ruby -v | grep "ruby" | awk '{print $2}'` = {{ ruby.cversion }} && echo True
  register: result
  ignore_errors: yes

- name: Download Source
  get_url: url=ftp://ftp.ruby-lang.org/pub/ruby/{{ ruby.mversion }}/ruby-{{ ruby.fversion }}.tar.gz dest=/tmp/
  when: result|failed

- name: Unzip
  unarchive: src=/tmp/ruby-{{ ruby.fversion }}.tar.gz dest=/tmp copy=no group={{ app.group }} owner={{ app.user }}
  when: result|failed

- name: Take Ownership of Directory
  file: path=/tmp/ruby-{{ ruby.fversion }} owner={{ app.user }} group={{ app.group }}
  sudo: yes
  when: result|failed

- name: Change Directory &  Configure
  shell: ./configure chdir=/tmp/ruby-{{ ruby.fversion }}
  sudo: yes
  when: result|failed

- name: Make
  shell: /usr/bin/make chdir=/tmp/ruby-{{ ruby.fversion }}
  sudo: yes
  when: result|failed

- name: Make Install
  shell: /usr/bin/make install chdir=/tmp/ruby-{{ ruby.fversion }}/
  sudo: yes
  when: result|failed

- name: Install Bundler
  gem: name=bundler state=present user_install=no
  sudo: yes
  when: result|failed
